apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cistic-odpadu
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
