apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cistic-odpadu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cistic-odpadu
  template:
    metadata:
      labels:
        name: strimzi-cistic-odpadu
    spec:
      serviceAccountName: strimzi-cistic-odpadu
      containers:
        - name: strimzi-cistic-odpadu
          image: quay.io/scholzj/strimzi-cistic-odpadu:latest
          ports:
            - containerPort: 8080
              name: http
          args:
            - "/work/application"
            - "--refresh=60000"
  strategy:
    type: Recreate
