apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: strimzi-drain-cleaner
  labels:
    app: strimzi-drain-cleaner
webhooks:
  - name: strimzi-drain-cleaner.strimzi.io
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods/eviction"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: "strimzi-drain-cleaner"
        name: "strimzi-drain-cleaner"
        path: /drainer
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVU01BS2hoZTNPUWVCK0hLSEdVamVWT0NVOTg4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNRMW94RHpBTkJnTlZCQWNUQmxCeVlXZDFaVEVlTUJ3R0ExVUVDaE1WVTNSeQphVzE2YVNCRWNtRnBiaUJEYkdWaGJtVnlNUjR3SEFZRFZRUURFeFZUZEhKcGJYcHBSSEpoYVc1RGJHVmhibVZ5ClEwRXdIaGNOTWpBeE1qSXpNVEV6TXpBd1doY05NalV4TWpJeU1URXpNekF3V2pCZU1Rc3dDUVlEVlFRR0V3SkQKV2pFUE1BMEdBMVVFQnhNR1VISmhaM1ZsTVI0d0hBWURWUVFLRXhWVGRISnBiWHBwSUVSeVlXbHVJRU5zWldGdQpaWEl4SGpBY0JnTlZCQU1URlZOMGNtbHRlbWxFY21GcGJrTnNaV0Z1WlhKRFFUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFONWE5clk3M3RDR0o5ejViMXVhTlR6Z1h4TnUzbGhUZ2FwOElhMDUKUUYvMXR2Nkc2UzBQSDh5aXZYY25xb2xUa3dzUC9MOEM2ZUNpeVBZbGlBKy9xaDBnUENoYXFUREdpWjZBaUVURwpjZFd0cUUzV1Q0NVJmOVNWbmU5bUZXdlA3WGNaS1orcTk5NlREeUxFVVQxRS9FTUtqYXZVN0xJb2dBdmNlaDVWCnkwS2dWa29zK1pJNWVieC9heGd1MlNMUGxITmVLamdTQTNFU3pIcWFhQTVPS0pVVm1mZmhaUWRicXpZcnBteGwKMU1GcUhBbHBnVFlDRmtlS1dUb2pZb0hvSFFiQlhOc2o2d2FaTGNoOFBOTFJac093OGNiQWJheEhpQnZUcWJzYQpxZysvWGozdjVCMS9CQ2tXeEVqcHNUUzlkSFNBaDVDbHV3REdqVmJETUhuS2cwTUNBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSUd5dnJWeGdWLzIKSitVK3MyaFhJZnovZi9ock1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2p2enR5SDJjdDY2Vm1xVnBnS20rSgpDc3d6b0V5Niszb1VSZjZnMnZnaUJtQUtZSHViWWZJaVlpaTRXaEFTRkdUcXJYV1dadk5CSHRUWjZXRUhZNW4rCkYvV0x5eUsrYVRMaFZpcTJ4SGtPbGlhTDl1aXpGMnk3N0xYY0NtamNHT01XNm5FQTdRaVZFaTYxNDMzcnlsaUMKSFM3ZitiWEw4dXBwQVBvMjluQ3pWdFI5SnBvYnE2VVJGdmE2Mm91V3pDdmZUWXNVZ3U2d3Nyc0lwTFplWGVUbQpVTmhFZHY4cWI3QmhCRVA4dTYxTTh2VFNBcUxNOEJyY3ExS3JJN3gvSllzaG81eEk3cTlhZ3FTZmsrRS9EU0xFCnVJM2wvdDl0OVd3TFJvUFViT0RtSTM2ZVg1NHpJem9OK3dZMk5TQmQrbXRtNDd2MGlLalJJTUp6SGdFMHY4QVEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5